(in-package html-base)

(register-character-entity-set :htmlspecial "-//W3C//ENTITIES Special//EN//HTML")

(define-character-entity :htmlspecial "quot" 34)
(define-character-entity :htmlspecial "amp" 38)
(define-character-entity :htmlspecial "lt" 60)
(define-character-entity :htmlspecial "gt" 62)
(define-character-entity :htmlspecial "OElig" 338)
(define-character-entity :htmlspecial "oelig" 339)
(define-character-entity :htmlspecial "Scaron" 352)
(define-character-entity :htmlspecial "scaron" 353)
(define-character-entity :htmlspecial "Yuml" 376)
(define-character-entity :htmlspecial "circ" 710)
(define-character-entity :htmlspecial "tilde" 732)
(define-character-entity :htmlspecial "ensp" 8194)
(define-character-entity :htmlspecial "emsp" 8195)
(define-character-entity :htmlspecial "thinsp" 8201)
(define-character-entity :htmlspecial "zwnj" 8204)
(define-character-entity :htmlspecial "zwj" 8205)
(define-character-entity :htmlspecial "lrm" 8206)
(define-character-entity :htmlspecial "rlm" 8207)
(define-character-entity :htmlspecial "ndash" 8211)
(define-character-entity :htmlspecial "mdash" 8212)
(define-character-entity :htmlspecial "lsquo" 8216)
(define-character-entity :htmlspecial "rsquo" 8217)
(define-character-entity :htmlspecial "sbquo" 8218)
(define-character-entity :htmlspecial "ldquo" 8220)
(define-character-entity :htmlspecial "rdquo" 8221)
(define-character-entity :htmlspecial "bdquo" 8222)
(define-character-entity :htmlspecial "dagger" 8224)
(define-character-entity :htmlspecial "Dagger" 8225)
(define-character-entity :htmlspecial "permil" 8240)
(define-character-entity :htmlspecial "lsaquo" 8249)
(define-character-entity :htmlspecial "rsaquo" 8250)
(define-character-entity :htmlspecial "euro" 8364)
